version: 2
jobs:
  codechecks:
    docker:
      - image: circleci/node:8.11.2-stretch
    steps:
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - checkout
      - restore_cache:
            keys:
            - v3-dependencies-{{ checksum "package.json" }}
      - run: PUBLIC_URL=. ENV=dev yarn build
      - run: yarn codechecks
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # needed for dtslint
      - run: mkdir /home/circleci/.dts/perf -p   	  
      # run tests!
      - run: yarn cover

      - run: bash <(curl -s https://codecov.io/bash)
